name: CI Pipeline

on:
  push:
    branches: [master]  # Запускать только при пуше в ветку master

jobs:
  build:
    runs-on: ubuntu-latest  # Используем GitHub-hosted runner с Ubuntu

    steps:
      - uses: actions/checkout@v3  # Клонирует код из репозитория

      - name: Установка зависимостей
        run: npm ci

      - name: Линтинг
        run: npm run lint

      - name: Тестирование
        run: npm run test

      - name: Сборка
        run: docker build -t ${{ secrets.DOCKER_USER }}/dovops-node-starter:${{ github.sha }} .